# Generated by Django 4.1.2 on 2022-11-10 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('pickup', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('order_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.IntegerField(default=0)),
                ('name', models.CharField(default='NoName', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('description', models.TextField(default='Description not specified')),
                ('composition', models.TextField(default='Сomposition not specified')),
                ('product_rating', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='PetApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default='No Text')),
                ('order', models.ManyToManyField(through='PetApp.OrderReview', to='PetApp.order')),
                ('product', models.ManyToManyField(through='PetApp.ProductReview', to='PetApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=50, unique=True)),
                ('seller_rating', models.FloatField(default=0.0)),
                ('contacts', models.TextField(default='The seller did not specify his contacts')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.siteuser')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(through='PetApp.SiteUserReview', to='PetApp.siteuser'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.review'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='PetApp.seller'),
        ),
        migrations.CreateModel(
            name='OrderSiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.siteuser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='orderreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.review'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ManyToManyField(through='PetApp.OrderSiteUser', to='PetApp.siteuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='PetApp.ProductOrder', to='PetApp.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.seller'),
        ),
    ]
