# Generated by Django 4.1.2 on 2022-10-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='composition',
            field=models.TextField(default='Сomposition not specified'),
        ),
        migrations.AddField(
            model_name='goods',
            name='product_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='contacts',
            field=models.TextField(default='The seller did not specify his contacts'),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='NoName', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(default='Description not specified'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(default='No Text'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(default='NoName', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('pickup', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('order_rating', models.IntegerField(default=0)),
                ('goods', models.ManyToManyField(through='PetApp.GoodsOrder', to='PetApp.goods')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.seller')),
            ],
        ),
        migrations.AddField(
            model_name='goodsorder',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.goods'),
        ),
        migrations.AddField(
            model_name='goodsorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.order'),
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.category')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ManyToManyField(through='PetApp.GoodsCategory', to='PetApp.category'),
        ),
    ]
