# Generated by Django 4.1.2 on 2022-10-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0002_goodsorder_goods_composition_goods_product_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.order')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.review')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.goods')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetApp.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ManyToManyField(through='PetApp.OrderReview', to='PetApp.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(through='PetApp.GoodsReview', to='PetApp.goods'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ManyToManyField(through='PetApp.SiteUserReview', to='PetApp.siteuser'),
        ),
    ]
